### ISSUE TITLE
RFID reader/writer Roboter(ROS2) Interaktivität herstellen

### ISSUE THREAD

**Issue by Al3xAda** [Lorenzuser/Projekt--HomeDirect#13]
Anfängliche Entwicklungs-Basis für eine Node, die RFID nutzt, erstellen.
Später soll sie mit dem Navigationsprogramm interagieren

### Tasks

- [x]  https://github.com/Lorenzuser/HomeDirect_ws/issues/2
- [ ] https://github.com/Lorenzuser/HomeDirect_ws/issues/3
- [ ] https://github.com/Lorenzuser/HomeDirect_ws/issues/6
- [x] https://github.com/Lorenzuser/HomeDirect_ws/issues/8

**Comment by Al3xAda** [comment]
- deadline extended

**Comment by Al3xAda** [comment]
Publishen nun möglich, subscriber muss noch getestet werden wobei `ros2 topic echo /tag_info` funktioniert

![Image](https://github.com/Lorenzuser/Projekt--HomeDirect/assets/123410382/b80ecf72-0161-42b6-9f26-90c34e0f0dcf)

**Comment by Al3xAda** [comment]
deadline extended

**Comment by Al3xAda** [comment]
deadline knapp verfehlt, jedoch nicht alle Ziele bei Tasks erfüllt
